package pdv.milotin.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_homely{

public static void LS_general(anywheresoftware.b4a.BA ba, android.view.View parent, anywheresoftware.b4a.keywords.LayoutValues lv, java.util.Map props,
java.util.Map<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) throws Exception {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
anywheresoftware.b4a.keywords.LayoutBuilder.scaleAll(views);
views.get("lbltop").vw.setWidth((int)((100d / 100 * width)));
views.get("lbltop").vw.setHeight((int)((60d * scale)));
views.get("lbltop").vw.setLeft((int)((0d / 100 * width)));
views.get("lbltop").vw.setTop((int)((0d / 100 * height)));
views.get("btnadd").vw.setWidth((int)((20d / 100 * width)));
views.get("btnadd").vw.setHeight((int)((60d * scale)));
views.get("btnadd").vw.setLeft((int)((15d / 100 * width)));
views.get("btnadd").vw.setTop((int)((0d / 100 * height)));
views.get("imgmenu").vw.setWidth((int)((30d * scale)));
views.get("imgmenu").vw.setHeight((int)((30d * scale)));
views.get("imgmenu").vw.setLeft((int)((3d / 100 * width)));
views.get("imgmenu").vw.setTop((int)((views.get("lbltop").vw.getTop() + views.get("lbltop").vw.getHeight()/2) - (views.get("imgmenu").vw.getHeight() / 2)));
views.get("imgavatar").vw.setWidth((int)((60d * scale)));
views.get("imgavatar").vw.setHeight((int)((60d * scale)));
views.get("imgavatar").vw.setLeft((int)((views.get("lbltop").vw.getLeft() + views.get("lbltop").vw.getWidth())-(5d / 100 * width) - (views.get("imgavatar").vw.getWidth())));
views.get("imgavatar").vw.setTop((int)((2d / 100 * height)));
views.get("pnheader1").vw.setWidth((int)((100d / 100 * width)));
views.get("pnheader1").vw.setHeight((int)((250d * scale)));
views.get("pnheader1").vw.setLeft((int)((0d / 100 * width)));
views.get("pnheader1").vw.setTop((int)((0d / 100 * height)));
views.get("lblheaderbg").vw.setWidth((int)((90d / 100 * width)));
views.get("lblheaderbg").vw.setHeight((int)((180d * scale)));
views.get("lblheaderbg").vw.setLeft((int)((50d / 100 * width) - (views.get("lblheaderbg").vw.getWidth() / 2)));
views.get("lblheaderbg").vw.setTop((int)((views.get("pnheader1").vw.getTop() + views.get("pnheader1").vw.getHeight()/2)));
views.get("lblwalletname").vw.setWidth((int)((80d / 100 * width)));
views.get("lblwalletname").vw.setHeight((int)((40d * scale)));
views.get("lblwalletname").vw.setLeft((int)((50d / 100 * width) - (views.get("lblwalletname").vw.getWidth() / 2)));
views.get("lblwalletname").vw.setTop((int)((views.get("lblheaderbg").vw.getTop()) - (views.get("lblwalletname").vw.getHeight())));
views.get("lblheader1").vw.setWidth((int)((40d / 100 * width)));
views.get("lblheader1").vw.setHeight((int)((40d * scale)));
views.get("lblheader1").vw.setLeft((int)((views.get("lblheaderbg").vw.getLeft())+(5d / 100 * width)));
views.get("lblheader1").vw.setTop((int)((views.get("lblheaderbg").vw.getTop())+(1d / 100 * height)));
views.get("lblheader2").vw.setWidth((int)((40d / 100 * width)));
views.get("lblheader2").vw.setHeight((int)((40d * scale)));
views.get("lblheader2").vw.setLeft((int)((views.get("lblheaderbg").vw.getLeft() + views.get("lblheaderbg").vw.getWidth())-(5d / 100 * width) - (views.get("lblheader2").vw.getWidth())));
views.get("lblheader2").vw.setTop((int)((views.get("lblheader1").vw.getTop())));
views.get("lblline1").vw.setWidth((int)((90d / 100 * width)));
views.get("lblline1").vw.setHeight((int)((20d * scale)));
views.get("lblline1").vw.setLeft((int)((views.get("lblheaderbg").vw.getLeft())));
views.get("lblline1").vw.setTop((int)((views.get("lblheader1").vw.getTop() + views.get("lblheader1").vw.getHeight())));
views.get("lbltotal").vw.setWidth((int)((90d * scale)));
views.get("lbltotal").vw.setHeight((int)((90d * scale)));
views.get("lbltotal").vw.setLeft((int)((views.get("lblheader1").vw.getLeft())));
views.get("lbltotal").vw.setTop((int)((views.get("lblheader1").vw.getTop() + views.get("lblheader1").vw.getHeight())+(3d / 100 * height)));
views.get("imgtotal").vw.setWidth((int)((views.get("lbltotal").vw.getWidth())));
views.get("imgtotal").vw.setHeight((int)((views.get("lbltotal").vw.getHeight())));
views.get("imgtotal").vw.setLeft((int)((views.get("lbltotal").vw.getLeft())));
views.get("imgtotal").vw.setTop((int)((views.get("lbltotal").vw.getTop())));
views.get("lblamount").vw.setWidth((int)((55d / 100 * width)));
views.get("lblamount").vw.setHeight((int)((40d * scale)));
views.get("lblamount").vw.setLeft((int)((views.get("lblheader2").vw.getLeft() + views.get("lblheader2").vw.getWidth()) - (views.get("lblamount").vw.getWidth())));
views.get("lblamount").vw.setTop((int)((views.get("lbltotal").vw.getTop() + views.get("lbltotal").vw.getHeight()/2) - (views.get("lblamount").vw.getHeight() / 2)));
views.get("pnlistview").vw.setWidth((int)((90d / 100 * width)));
views.get("pnlistview").vw.setHeight((int)((45d / 100 * height)));
views.get("pnlistview").vw.setLeft((int)((50d / 100 * width) - (views.get("pnlistview").vw.getWidth() / 2)));
views.get("pnlistview").vw.setTop((int)((views.get("lblheaderbg").vw.getTop() + views.get("lblheaderbg").vw.getHeight())+(2.5d / 100 * height)));
views.get("clvhome").vw.setWidth((int)((90d / 100 * width)));
views.get("clvhome").vw.setHeight((int)((42d / 100 * height)));
views.get("clvhome").vw.setLeft((int)((0d / 100 * width)));
views.get("clvhome").vw.setTop((int)((2d / 100 * height)));
views.get("lblbottom").vw.setWidth((int)((100d / 100 * width)));
views.get("lblbottom").vw.setHeight((int)((80d * scale)));
views.get("lblbottom").vw.setLeft((int)((50d / 100 * width) - (views.get("lblbottom").vw.getWidth() / 2)));
views.get("lblbottom").vw.setTop((int)((100d / 100 * height) - (views.get("lblbottom").vw.getHeight())));
views.get("lblhome2").vw.setWidth((int)((25d / 100 * width)));
views.get("lblhome2").vw.setHeight((int)((20d * scale)));
views.get("lblhome2").vw.setLeft((int)((12.5d / 100 * width) - (views.get("lblhome2").vw.getWidth() / 2)));
views.get("lblhome2").vw.setTop((int)((views.get("lblbottom").vw.getTop() + views.get("lblbottom").vw.getHeight())-(1d / 100 * height) - (views.get("lblhome2").vw.getHeight())));
views.get("lblfund2").vw.setWidth((int)((views.get("lblhome2").vw.getWidth())));
views.get("lblfund2").vw.setHeight((int)((views.get("lblhome2").vw.getHeight())));
views.get("lblfund2").vw.setLeft((int)((37.5d / 100 * width) - (views.get("lblfund2").vw.getWidth() / 2)));
views.get("lblfund2").vw.setTop((int)((views.get("lblhome2").vw.getTop() + views.get("lblhome2").vw.getHeight()) - (views.get("lblfund2").vw.getHeight())));
views.get("lblhistory2").vw.setWidth((int)((views.get("lblhome2").vw.getWidth())));
views.get("lblhistory2").vw.setHeight((int)((views.get("lblhome2").vw.getHeight())));
views.get("lblhistory2").vw.setLeft((int)((62.5d / 100 * width) - (views.get("lblhistory2").vw.getWidth() / 2)));
views.get("lblhistory2").vw.setTop((int)((views.get("lblhome2").vw.getTop() + views.get("lblhome2").vw.getHeight()) - (views.get("lblhistory2").vw.getHeight())));
views.get("lbluser2").vw.setWidth((int)((views.get("lblhome2").vw.getWidth())));
views.get("lbluser2").vw.setHeight((int)((views.get("lblhome2").vw.getHeight())));
views.get("lbluser2").vw.setLeft((int)((87.5d / 100 * width) - (views.get("lbluser2").vw.getWidth() / 2)));
views.get("lbluser2").vw.setTop((int)((views.get("lblhome2").vw.getTop() + views.get("lblhome2").vw.getHeight()) - (views.get("lbluser2").vw.getHeight())));
views.get("lblhome").vw.setWidth((int)((25d * scale)));
views.get("lblhome").vw.setHeight((int)((25d * scale)));
views.get("lblhome").vw.setLeft((int)((12.5d / 100 * width) - (views.get("lblhome").vw.getWidth() / 2)));
views.get("lblhome").vw.setTop((int)((views.get("lblhome2").vw.getTop())-(1d / 100 * height) - (views.get("lblhome").vw.getHeight())));
views.get("lblfund").vw.setWidth((int)((views.get("lblhome").vw.getWidth())));
views.get("lblfund").vw.setHeight((int)((views.get("lblhome").vw.getHeight())));
views.get("lblfund").vw.setLeft((int)((37.5d / 100 * width) - (views.get("lblfund").vw.getWidth() / 2)));
views.get("lblfund").vw.setTop((int)((views.get("lblhome").vw.getTop() + views.get("lblhome").vw.getHeight()) - (views.get("lblfund").vw.getHeight())));
views.get("lblhistory").vw.setWidth((int)((views.get("lblhome").vw.getWidth())));
views.get("lblhistory").vw.setHeight((int)((views.get("lblhome").vw.getHeight())));
views.get("lblhistory").vw.setLeft((int)((62.5d / 100 * width) - (views.get("lblhistory").vw.getWidth() / 2)));
views.get("lblhistory").vw.setTop((int)((views.get("lblhome").vw.getTop() + views.get("lblhome").vw.getHeight()) - (views.get("lblhistory").vw.getHeight())));
views.get("lbluser").vw.setWidth((int)((views.get("lblhome").vw.getWidth())));
views.get("lbluser").vw.setHeight((int)((views.get("lblhome").vw.getHeight())));
views.get("lbluser").vw.setLeft((int)((87.5d / 100 * width) - (views.get("lbluser").vw.getWidth() / 2)));
views.get("lbluser").vw.setTop((int)((views.get("lblhome").vw.getTop() + views.get("lblhome").vw.getHeight()) - (views.get("lbluser").vw.getHeight())));

}
}