package pdv.milotin.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_kyc1listviewly{

public static void LS_general(anywheresoftware.b4a.BA ba, android.view.View parent, anywheresoftware.b4a.keywords.LayoutValues lv, java.util.Map props,
java.util.Map<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) throws Exception {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
anywheresoftware.b4a.keywords.LayoutBuilder.scaleAll(views);
views.get("lblcontactinfo").vw.setWidth((int)((70d / 100 * width)));
views.get("lblcontactinfo").vw.setHeight((int)((40d * scale)));
views.get("lblcontactinfo").vw.setLeft((int)((50d / 100 * width) - (views.get("lblcontactinfo").vw.getWidth() / 2)));
views.get("lblcontactinfo").vw.setTop((int)((0d / 100 * height)));
views.get("lblcontactinfo2").vw.setWidth((int)((views.get("lblcontactinfo").vw.getWidth())));
views.get("lblcontactinfo2").vw.setHeight((int)((20d * scale)));
views.get("lblcontactinfo2").vw.setLeft((int)((views.get("lblcontactinfo").vw.getLeft())));
views.get("lblcontactinfo2").vw.setTop((int)((views.get("lblcontactinfo").vw.getTop() + views.get("lblcontactinfo").vw.getHeight())));
views.get("lblfullname").vw.setWidth((int)((80d / 100 * width)));
views.get("lblfullname").vw.setHeight((int)((40d * scale)));
views.get("lblfullname").vw.setLeft((int)((50d / 100 * width) - (views.get("lblfullname").vw.getWidth() / 2)));
views.get("lblfullname").vw.setTop((int)((views.get("lblcontactinfo2").vw.getTop() + views.get("lblcontactinfo2").vw.getHeight())+(2d / 100 * height)));
views.get("pnfullname").vw.setWidth((int)((80d / 100 * width)));
views.get("pnfullname").vw.setHeight((int)((50d * scale)));
views.get("pnfullname").vw.setLeft((int)((50d / 100 * width) - (views.get("pnfullname").vw.getWidth() / 2)));
views.get("pnfullname").vw.setTop((int)((views.get("lblfullname").vw.getTop() + views.get("lblfullname").vw.getHeight())));
views.get("txtfullname").vw.setWidth((int)((60d / 100 * width)));
views.get("txtfullname").vw.setHeight((int)((70d * scale)));
views.get("txtfullname").vw.setLeft((int)((10d / 100 * width)));
views.get("txtfullname").vw.setTop((int)(0-(8d * scale)));
views.get("imgfullname").vw.setHeight((int)((20d * scale)));
views.get("imgfullname").vw.setWidth((int)((views.get("imgfullname").vw.getHeight())));
views.get("imgfullname").vw.setTop((int)((views.get("pnfullname").vw.getHeight())/2d-(views.get("imgfullname").vw.getHeight())/2d));
views.get("lblic").vw.setWidth((int)((views.get("lblfullname").vw.getWidth())));
views.get("lblic").vw.setHeight((int)((views.get("lblfullname").vw.getHeight())));
views.get("lblic").vw.setLeft((int)((views.get("lblfullname").vw.getLeft())));
views.get("lblic").vw.setTop((int)((views.get("pnfullname").vw.getTop() + views.get("pnfullname").vw.getHeight())));
views.get("pnic").vw.setWidth((int)((views.get("pnfullname").vw.getWidth())));
views.get("pnic").vw.setHeight((int)((views.get("pnfullname").vw.getHeight())));
views.get("pnic").vw.setLeft((int)((views.get("pnfullname").vw.getLeft())));
views.get("pnic").vw.setTop((int)((views.get("lblic").vw.getTop() + views.get("lblic").vw.getHeight())));
views.get("txtic").vw.setWidth((int)((views.get("txtfullname").vw.getWidth())));
views.get("txtic").vw.setHeight((int)((views.get("txtfullname").vw.getHeight())));
views.get("txtic").vw.setLeft((int)((views.get("txtfullname").vw.getLeft())));
views.get("txtic").vw.setTop((int)(0-(7d * scale)));
views.get("imgic").vw.setHeight((int)((20d * scale)));
views.get("imgic").vw.setWidth((int)((views.get("imgic").vw.getHeight())));
views.get("imgic").vw.setTop((int)((views.get("pnic").vw.getHeight())/2d-(views.get("imgic").vw.getHeight())/2d));
views.get("lbladdress").vw.setWidth((int)((views.get("lblfullname").vw.getWidth())));
views.get("lbladdress").vw.setHeight((int)((views.get("lblfullname").vw.getHeight())));
views.get("lbladdress").vw.setLeft((int)((views.get("lblfullname").vw.getLeft())));
views.get("lbladdress").vw.setTop((int)((views.get("pnic").vw.getTop() + views.get("pnic").vw.getHeight())));
views.get("pnaddress").vw.setWidth((int)((views.get("pnfullname").vw.getWidth())));
views.get("pnaddress").vw.setHeight((int)((views.get("pnfullname").vw.getHeight())));
views.get("pnaddress").vw.setLeft((int)((views.get("pnfullname").vw.getLeft())));
views.get("pnaddress").vw.setTop((int)((views.get("lbladdress").vw.getTop() + views.get("lbladdress").vw.getHeight())));
views.get("txtaddress").vw.setWidth((int)((views.get("txtfullname").vw.getWidth())));
views.get("txtaddress").vw.setHeight((int)((views.get("txtfullname").vw.getHeight())));
views.get("txtaddress").vw.setLeft((int)((views.get("txtfullname").vw.getLeft())));
views.get("txtaddress").vw.setTop((int)(0-(7d * scale)));
views.get("imgaddress").vw.setHeight((int)((20d * scale)));
views.get("imgaddress").vw.setWidth((int)((views.get("imgic").vw.getHeight())));
views.get("imgaddress").vw.setTop((int)((views.get("pnaddress").vw.getHeight())/2d-(views.get("imgaddress").vw.getHeight())/2d));
views.get("lblemail").vw.setWidth((int)((views.get("lblfullname").vw.getWidth())));
views.get("lblemail").vw.setHeight((int)((views.get("lblfullname").vw.getHeight())));
views.get("lblemail").vw.setLeft((int)((views.get("lblfullname").vw.getLeft())));
views.get("lblemail").vw.setTop((int)((views.get("pnaddress").vw.getTop() + views.get("pnaddress").vw.getHeight())));
views.get("pnemail").vw.setWidth((int)((views.get("pnfullname").vw.getWidth())));
views.get("pnemail").vw.setHeight((int)((views.get("pnfullname").vw.getHeight())));
views.get("pnemail").vw.setLeft((int)((views.get("pnfullname").vw.getLeft())));
views.get("pnemail").vw.setTop((int)((views.get("lblemail").vw.getTop() + views.get("lblemail").vw.getHeight())));
views.get("txtemail").vw.setWidth((int)((views.get("txtfullname").vw.getWidth())));
views.get("txtemail").vw.setHeight((int)((views.get("txtfullname").vw.getHeight())));
views.get("txtemail").vw.setLeft((int)((views.get("txtfullname").vw.getLeft())));
views.get("txtemail").vw.setTop((int)(0-(7d * scale)));
views.get("imgemail").vw.setHeight((int)((20d * scale)));
views.get("imgemail").vw.setWidth((int)((views.get("imgemail").vw.getHeight())));
views.get("imgemail").vw.setTop((int)((views.get("pnemail").vw.getHeight())/2d-(views.get("imgemail").vw.getHeight())/2d));
views.get("lblphone").vw.setWidth((int)((views.get("lblfullname").vw.getWidth())));
views.get("lblphone").vw.setHeight((int)((views.get("lblfullname").vw.getHeight())));
views.get("lblphone").vw.setLeft((int)((views.get("lblfullname").vw.getLeft())));
views.get("lblphone").vw.setTop((int)((views.get("pnemail").vw.getTop() + views.get("pnemail").vw.getHeight())));
views.get("pnphone").vw.setWidth((int)((views.get("pnfullname").vw.getWidth())));
views.get("pnphone").vw.setHeight((int)((views.get("pnfullname").vw.getHeight())));
views.get("pnphone").vw.setLeft((int)((views.get("pnfullname").vw.getLeft())));
views.get("pnphone").vw.setTop((int)((views.get("lblphone").vw.getTop() + views.get("lblphone").vw.getHeight())));
views.get("txtphone").vw.setWidth((int)((views.get("txtfullname").vw.getWidth())));
views.get("txtphone").vw.setHeight((int)((views.get("txtfullname").vw.getHeight())));
views.get("txtphone").vw.setLeft((int)((views.get("txtfullname").vw.getLeft())));
views.get("txtphone").vw.setTop((int)(0-(7d * scale)));
views.get("imgphone").vw.setHeight((int)((20d * scale)));
views.get("imgphone").vw.setWidth((int)((views.get("imgphone").vw.getHeight())));
views.get("imgphone").vw.setTop((int)((views.get("pnphone").vw.getHeight())/2d-(views.get("imgphone").vw.getHeight())/2d));
views.get("lblpassword").vw.setWidth((int)((views.get("lblfullname").vw.getWidth())));
views.get("lblpassword").vw.setHeight((int)((views.get("lblfullname").vw.getHeight())));
views.get("lblpassword").vw.setLeft((int)((views.get("lblfullname").vw.getLeft())));
views.get("lblpassword").vw.setTop((int)((views.get("pnphone").vw.getTop() + views.get("pnphone").vw.getHeight())));
views.get("pnpassword").vw.setWidth((int)((views.get("pnfullname").vw.getWidth())));
views.get("pnpassword").vw.setHeight((int)((views.get("pnfullname").vw.getHeight())));
views.get("pnpassword").vw.setLeft((int)((views.get("pnfullname").vw.getLeft())));
views.get("pnpassword").vw.setTop((int)((views.get("lblpassword").vw.getTop() + views.get("lblpassword").vw.getHeight())));
views.get("txtpassword").vw.setWidth((int)((views.get("txtfullname").vw.getWidth())));
views.get("txtpassword").vw.setHeight((int)((views.get("txtfullname").vw.getHeight())));
views.get("txtpassword").vw.setLeft((int)((views.get("txtfullname").vw.getLeft())));
views.get("txtpassword").vw.setTop((int)(0-(7d * scale)));
views.get("imgpassword").vw.setHeight((int)((20d * scale)));
views.get("imgpassword").vw.setWidth((int)((views.get("imgpassword").vw.getHeight())));
views.get("imgpassword").vw.setTop((int)((views.get("pnpassword").vw.getHeight())/2d-(views.get("imgpassword").vw.getHeight())/2d));
views.get("lblpassword2").vw.setWidth((int)((views.get("lblfullname").vw.getWidth())));
views.get("lblpassword2").vw.setHeight((int)((views.get("lblfullname").vw.getHeight())));
views.get("lblpassword2").vw.setLeft((int)((views.get("lblfullname").vw.getLeft())));
views.get("lblpassword2").vw.setTop((int)((views.get("pnpassword").vw.getTop() + views.get("pnpassword").vw.getHeight())));
views.get("pnpassword2").vw.setWidth((int)((views.get("pnfullname").vw.getWidth())));
views.get("pnpassword2").vw.setHeight((int)((views.get("pnfullname").vw.getHeight())));
views.get("pnpassword2").vw.setLeft((int)((views.get("pnfullname").vw.getLeft())));
views.get("pnpassword2").vw.setTop((int)((views.get("lblpassword2").vw.getTop() + views.get("lblpassword2").vw.getHeight())));
views.get("txtpassword2").vw.setWidth((int)((views.get("txtfullname").vw.getWidth())));
views.get("txtpassword2").vw.setHeight((int)((views.get("txtfullname").vw.getHeight())));
views.get("txtpassword2").vw.setLeft((int)((views.get("txtfullname").vw.getLeft())));
views.get("txtpassword2").vw.setTop((int)(0-(7d * scale)));
views.get("imgpassword2").vw.setHeight((int)((20d * scale)));
views.get("imgpassword2").vw.setWidth((int)((views.get("imgpassword2").vw.getHeight())));
views.get("imgpassword2").vw.setTop((int)((views.get("pnpassword2").vw.getHeight())/2d-(views.get("imgpassword2").vw.getHeight())/2d));
views.get("btncontinue1").vw.setWidth((int)((80d / 100 * width)));
views.get("btncontinue1").vw.setHeight((int)((50d * scale)));
views.get("btncontinue1").vw.setLeft((int)((50d / 100 * width) - (views.get("btncontinue1").vw.getWidth() / 2)));
views.get("btncontinue1").vw.setTop((int)((views.get("pnpassword2").vw.getTop() + views.get("pnpassword2").vw.getHeight())+(5d / 100 * height)));

}
}