package pdv.milotin.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_listviewly2{

public static void LS_general(anywheresoftware.b4a.BA ba, android.view.View parent, anywheresoftware.b4a.keywords.LayoutValues lv, java.util.Map props,
java.util.Map<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) throws Exception {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
anywheresoftware.b4a.keywords.LayoutBuilder.scaleAll(views);
views.get("imgstatus1").vw.setWidth((int)((30d * scale)));
views.get("imgstatus1").vw.setHeight((int)((30d * scale)));
views.get("imgstatus1").vw.setLeft((int)((4d / 100 * width)));
views.get("imgstatus1").vw.setTop((int)((2d / 100 * height)));
views.get("lblhistorytitle").vw.setWidth((int)((60d / 100 * width)));
views.get("lblhistorytitle").vw.setHeight((int)((20d * scale)));
views.get("lblhistorytitle").vw.setLeft((int)((views.get("imgstatus1").vw.getLeft() + views.get("imgstatus1").vw.getWidth())+(2d / 100 * width)));
views.get("lblhistorytitle").vw.setTop((int)((views.get("imgstatus1").vw.getTop() + views.get("imgstatus1").vw.getHeight()/2) - (views.get("lblhistorytitle").vw.getHeight())));
views.get("lblhistoryamount").vw.setWidth((int)((25d / 100 * width)));
views.get("lblhistoryamount").vw.setHeight((int)((views.get("lblhistorytitle").vw.getHeight())));
views.get("lblhistoryamount").vw.setLeft((int)((views.get("lblhistorytitle").vw.getLeft() + views.get("lblhistorytitle").vw.getWidth())));
views.get("lblhistoryamount").vw.setTop((int)((views.get("imgstatus1").vw.getTop() + views.get("imgstatus1").vw.getHeight()/2) - (views.get("lblhistoryamount").vw.getHeight() / 2)));
views.get("lblhistoryhashid").vw.setWidth((int)((30d / 100 * width)));
views.get("lblhistoryhashid").vw.setHeight((int)((views.get("lblhistorytitle").vw.getHeight())));
views.get("lblhistoryhashid").vw.setLeft((int)((views.get("lblhistorytitle").vw.getLeft())));
views.get("lblhistoryhashid").vw.setTop((int)((views.get("lblhistorytitle").vw.getTop() + views.get("lblhistorytitle").vw.getHeight())));
views.get("lblhistorydate").vw.setWidth((int)((28d / 100 * width)));
views.get("lblhistorydate").vw.setHeight((int)((views.get("lblhistorytitle").vw.getHeight())));
views.get("lblhistorydate").vw.setLeft((int)((views.get("lblhistorytitle").vw.getLeft() + views.get("lblhistorytitle").vw.getWidth()) - (views.get("lblhistorydate").vw.getWidth())));
views.get("lblhistorydate").vw.setTop((int)((views.get("lblhistorytitle").vw.getTop() + views.get("lblhistorytitle").vw.getHeight())));
views.get("lblsaperate").vw.setWidth((int)((100d / 100 * width)));
views.get("lblsaperate").vw.setHeight((int)((1d * scale)));
views.get("lblsaperate").vw.setLeft((int)((0d / 100 * width)));
views.get("lblsaperate").vw.setTop((int)((views.get("lblhistorydate").vw.getTop() + views.get("lblhistorydate").vw.getHeight())+(1d / 100 * height)));
views.get("imgstatus2").vw.setWidth((int)((30d * scale)));
views.get("imgstatus2").vw.setHeight((int)((30d * scale)));
views.get("imgstatus2").vw.setLeft((int)((views.get("imgstatus1").vw.getLeft())));
views.get("imgstatus2").vw.setTop((int)((views.get("lblsaperate").vw.getTop() + views.get("lblsaperate").vw.getHeight())+(2d / 100 * height)));
views.get("lblhistorytitle2").vw.setWidth((int)((60d / 100 * width)));
views.get("lblhistorytitle2").vw.setHeight((int)((20d * scale)));
views.get("lblhistorytitle2").vw.setLeft((int)((views.get("imgstatus2").vw.getLeft() + views.get("imgstatus2").vw.getWidth())+(2d / 100 * width)));
views.get("lblhistorytitle2").vw.setTop((int)((views.get("imgstatus2").vw.getTop() + views.get("imgstatus2").vw.getHeight()/2) - (views.get("lblhistorytitle2").vw.getHeight())));
views.get("lblhistoryamount2").vw.setWidth((int)((25d / 100 * width)));
views.get("lblhistoryamount2").vw.setHeight((int)((views.get("lblhistorytitle2").vw.getHeight())));
views.get("lblhistoryamount2").vw.setLeft((int)((views.get("lblhistorytitle2").vw.getLeft() + views.get("lblhistorytitle2").vw.getWidth())));
views.get("lblhistoryamount2").vw.setTop((int)((views.get("imgstatus2").vw.getTop() + views.get("imgstatus2").vw.getHeight()/2) - (views.get("lblhistoryamount2").vw.getHeight() / 2)));
views.get("lblhistoryhashid2").vw.setWidth((int)((30d / 100 * width)));
views.get("lblhistoryhashid2").vw.setHeight((int)((views.get("lblhistorytitle2").vw.getHeight())));
views.get("lblhistoryhashid2").vw.setLeft((int)((views.get("lblhistorytitle2").vw.getLeft())));
views.get("lblhistoryhashid2").vw.setTop((int)((views.get("lblhistorytitle2").vw.getTop() + views.get("lblhistorytitle2").vw.getHeight())));
views.get("lblhistorydate2").vw.setWidth((int)((28d / 100 * width)));
views.get("lblhistorydate2").vw.setHeight((int)((views.get("lblhistorytitle2").vw.getHeight())));
views.get("lblhistorydate2").vw.setLeft((int)((views.get("lblhistorytitle2").vw.getLeft() + views.get("lblhistorytitle2").vw.getWidth()) - (views.get("lblhistorydate2").vw.getWidth())));
views.get("lblhistorydate2").vw.setTop((int)((views.get("lblhistorytitle2").vw.getTop() + views.get("lblhistorytitle2").vw.getHeight())));
views.get("lblsaperate2").vw.setWidth((int)((100d / 100 * width)));
views.get("lblsaperate2").vw.setHeight((int)((1d * scale)));
views.get("lblsaperate2").vw.setLeft((int)((0d / 100 * width)));
views.get("lblsaperate2").vw.setTop((int)((views.get("lblhistorydate2").vw.getTop() + views.get("lblhistorydate2").vw.getHeight())+(1d / 100 * height)));
views.get("imgstatus3").vw.setWidth((int)((30d * scale)));
views.get("imgstatus3").vw.setHeight((int)((30d * scale)));
views.get("imgstatus3").vw.setLeft((int)((views.get("imgstatus1").vw.getLeft())));
views.get("imgstatus3").vw.setTop((int)((views.get("lblsaperate2").vw.getTop() + views.get("lblsaperate2").vw.getHeight())+(2d / 100 * height)));
views.get("lblhistorytitle3").vw.setWidth((int)((60d / 100 * width)));
views.get("lblhistorytitle3").vw.setHeight((int)((20d * scale)));
views.get("lblhistorytitle3").vw.setLeft((int)((views.get("imgstatus3").vw.getLeft() + views.get("imgstatus3").vw.getWidth())+(2d / 100 * width)));
views.get("lblhistorytitle3").vw.setTop((int)((views.get("imgstatus3").vw.getTop() + views.get("imgstatus3").vw.getHeight()/2) - (views.get("lblhistorytitle3").vw.getHeight())));
views.get("lblhistoryamount3").vw.setWidth((int)((25d / 100 * width)));
views.get("lblhistoryamount3").vw.setHeight((int)((views.get("lblhistorytitle3").vw.getHeight())));
views.get("lblhistoryamount3").vw.setLeft((int)((views.get("lblhistorytitle3").vw.getLeft() + views.get("lblhistorytitle3").vw.getWidth())));
views.get("lblhistoryamount3").vw.setTop((int)((views.get("imgstatus3").vw.getTop() + views.get("imgstatus3").vw.getHeight()/2) - (views.get("lblhistoryamount3").vw.getHeight() / 2)));
views.get("lblhistoryhashid3").vw.setWidth((int)((30d / 100 * width)));
views.get("lblhistoryhashid3").vw.setHeight((int)((views.get("lblhistorytitle3").vw.getHeight())));
views.get("lblhistoryhashid3").vw.setLeft((int)((views.get("lblhistorytitle3").vw.getLeft())));
views.get("lblhistoryhashid3").vw.setTop((int)((views.get("lblhistorytitle3").vw.getTop() + views.get("lblhistorytitle3").vw.getHeight())));
views.get("lblhistorydate3").vw.setWidth((int)((28d / 100 * width)));
views.get("lblhistorydate3").vw.setHeight((int)((views.get("lblhistorytitle3").vw.getHeight())));
views.get("lblhistorydate3").vw.setLeft((int)((views.get("lblhistorytitle3").vw.getLeft() + views.get("lblhistorytitle3").vw.getWidth()) - (views.get("lblhistorydate3").vw.getWidth())));
views.get("lblhistorydate3").vw.setTop((int)((views.get("lblhistorytitle3").vw.getTop() + views.get("lblhistorytitle3").vw.getHeight())));
views.get("lblsaperate3").vw.setWidth((int)((100d / 100 * width)));
views.get("lblsaperate3").vw.setHeight((int)((1d * scale)));
views.get("lblsaperate3").vw.setLeft((int)((0d / 100 * width)));
views.get("lblsaperate3").vw.setTop((int)((views.get("lblhistorydate3").vw.getTop() + views.get("lblhistorydate3").vw.getHeight())+(1d / 100 * height)));
views.get("imgstatus4").vw.setWidth((int)((30d * scale)));
views.get("imgstatus4").vw.setHeight((int)((30d * scale)));
views.get("imgstatus4").vw.setLeft((int)((views.get("imgstatus1").vw.getLeft())));
views.get("imgstatus4").vw.setTop((int)((views.get("lblsaperate3").vw.getTop() + views.get("lblsaperate3").vw.getHeight())+(2d / 100 * height)));
views.get("lblhistorytitle4").vw.setWidth((int)((60d / 100 * width)));
views.get("lblhistorytitle4").vw.setHeight((int)((20d * scale)));
views.get("lblhistorytitle4").vw.setLeft((int)((views.get("imgstatus4").vw.getLeft() + views.get("imgstatus4").vw.getWidth())+(2d / 100 * width)));
views.get("lblhistorytitle4").vw.setTop((int)((views.get("imgstatus4").vw.getTop() + views.get("imgstatus4").vw.getHeight()/2) - (views.get("lblhistorytitle4").vw.getHeight())));
views.get("lblhistoryamount4").vw.setWidth((int)((25d / 100 * width)));
views.get("lblhistoryamount4").vw.setHeight((int)((views.get("lblhistorytitle4").vw.getHeight())));
views.get("lblhistoryamount4").vw.setLeft((int)((views.get("lblhistorytitle4").vw.getLeft() + views.get("lblhistorytitle4").vw.getWidth())));
views.get("lblhistoryamount4").vw.setTop((int)((views.get("imgstatus4").vw.getTop() + views.get("imgstatus4").vw.getHeight()/2) - (views.get("lblhistoryamount4").vw.getHeight() / 2)));
views.get("lblhistoryhashid4").vw.setWidth((int)((30d / 100 * width)));
views.get("lblhistoryhashid4").vw.setHeight((int)((views.get("lblhistorytitle4").vw.getHeight())));
views.get("lblhistoryhashid4").vw.setLeft((int)((views.get("lblhistorytitle4").vw.getLeft())));
views.get("lblhistoryhashid4").vw.setTop((int)((views.get("lblhistorytitle4").vw.getTop() + views.get("lblhistorytitle4").vw.getHeight())));
views.get("lblhistorydate4").vw.setWidth((int)((28d / 100 * width)));
views.get("lblhistorydate4").vw.setHeight((int)((views.get("lblhistorytitle4").vw.getHeight())));
views.get("lblhistorydate4").vw.setLeft((int)((views.get("lblhistorytitle4").vw.getLeft() + views.get("lblhistorytitle4").vw.getWidth()) - (views.get("lblhistorydate4").vw.getWidth())));
views.get("lblhistorydate4").vw.setTop((int)((views.get("lblhistorytitle4").vw.getTop() + views.get("lblhistorytitle4").vw.getHeight())));
views.get("lblsaperate4").vw.setWidth((int)((100d / 100 * width)));
views.get("lblsaperate4").vw.setHeight((int)((1d * scale)));
views.get("lblsaperate4").vw.setLeft((int)((0d / 100 * width)));
views.get("lblsaperate4").vw.setTop((int)((views.get("lblhistorydate4").vw.getTop() + views.get("lblhistorydate4").vw.getHeight())+(1d / 100 * height)));
views.get("imgstatus5").vw.setWidth((int)((30d * scale)));
views.get("imgstatus5").vw.setHeight((int)((30d * scale)));
views.get("imgstatus5").vw.setLeft((int)((views.get("imgstatus1").vw.getLeft())));
views.get("imgstatus5").vw.setTop((int)((views.get("lblsaperate4").vw.getTop() + views.get("lblsaperate4").vw.getHeight())+(2d / 100 * height)));
views.get("lblhistorytitle5").vw.setWidth((int)((60d / 100 * width)));
views.get("lblhistorytitle5").vw.setHeight((int)((20d * scale)));
views.get("lblhistorytitle5").vw.setLeft((int)((views.get("imgstatus5").vw.getLeft() + views.get("imgstatus5").vw.getWidth())+(2d / 100 * width)));
views.get("lblhistorytitle5").vw.setTop((int)((views.get("imgstatus5").vw.getTop() + views.get("imgstatus5").vw.getHeight()/2) - (views.get("lblhistorytitle5").vw.getHeight())));
views.get("lblhistoryamount5").vw.setWidth((int)((25d / 100 * width)));
views.get("lblhistoryamount5").vw.setHeight((int)((views.get("lblhistorytitle5").vw.getHeight())));
views.get("lblhistoryamount5").vw.setLeft((int)((views.get("lblhistorytitle5").vw.getLeft() + views.get("lblhistorytitle5").vw.getWidth())));
views.get("lblhistoryamount5").vw.setTop((int)((views.get("imgstatus5").vw.getTop() + views.get("imgstatus5").vw.getHeight()/2) - (views.get("lblhistoryamount5").vw.getHeight() / 2)));
views.get("lblhistoryhashid5").vw.setWidth((int)((30d / 100 * width)));
views.get("lblhistoryhashid5").vw.setHeight((int)((views.get("lblhistorytitle5").vw.getHeight())));
views.get("lblhistoryhashid5").vw.setLeft((int)((views.get("lblhistorytitle5").vw.getLeft())));
views.get("lblhistoryhashid5").vw.setTop((int)((views.get("lblhistorytitle5").vw.getTop() + views.get("lblhistorytitle5").vw.getHeight())));
views.get("lblhistorydate5").vw.setWidth((int)((28d / 100 * width)));
views.get("lblhistorydate5").vw.setHeight((int)((views.get("lblhistorytitle5").vw.getHeight())));
views.get("lblhistorydate5").vw.setLeft((int)((views.get("lblhistorytitle5").vw.getLeft() + views.get("lblhistorytitle5").vw.getWidth()) - (views.get("lblhistorydate5").vw.getWidth())));
views.get("lblhistorydate5").vw.setTop((int)((views.get("lblhistorytitle5").vw.getTop() + views.get("lblhistorytitle5").vw.getHeight())));

}
}