package pdv.milotin.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_userly{

public static void LS_general(anywheresoftware.b4a.BA ba, android.view.View parent, anywheresoftware.b4a.keywords.LayoutValues lv, java.util.Map props,
java.util.Map<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) throws Exception {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
anywheresoftware.b4a.keywords.LayoutBuilder.scaleAll(views);
views.get("lbltop").vw.setWidth((int)((100d / 100 * width)));
views.get("lbltop").vw.setHeight((int)((60d * scale)));
views.get("lbltop").vw.setLeft((int)((0d / 100 * width)));
views.get("lbltop").vw.setTop((int)((0d / 100 * height)));
views.get("imgback").vw.setWidth((int)((30d * scale)));
views.get("imgback").vw.setHeight((int)((30d * scale)));
views.get("imgback").vw.setLeft((int)((3d / 100 * width)));
views.get("imgback").vw.setTop((int)((views.get("lbltop").vw.getTop() + views.get("lbltop").vw.getHeight()/2) - (views.get("imgback").vw.getHeight() / 2)));
views.get("imgkyc").vw.setWidth((int)((30d * scale)));
views.get("imgkyc").vw.setHeight((int)((30d * scale)));
views.get("imgkyc").vw.setLeft((int)((97d / 100 * width) - (views.get("imgkyc").vw.getWidth())));
views.get("imgkyc").vw.setTop((int)((views.get("lbltop").vw.getTop() + views.get("lbltop").vw.getHeight()/2) - (views.get("imgkyc").vw.getHeight() / 2)));
views.get("pnheader1").vw.setWidth((int)((100d / 100 * width)));
views.get("pnheader1").vw.setHeight((int)((250d * scale)));
views.get("pnheader1").vw.setLeft((int)((0d / 100 * width)));
views.get("pnheader1").vw.setTop((int)((0d / 100 * height)));
views.get("pnframe2").vw.setWidth((int)((90d / 100 * width)));
views.get("pnframe2").vw.setHeight((int)((79d / 100 * height)));
views.get("pnframe2").vw.setLeft((int)((50d / 100 * width) - (views.get("pnframe2").vw.getWidth() / 2)));
views.get("pnframe2").vw.setTop((int)((views.get("lbltop").vw.getTop() + views.get("lbltop").vw.getHeight())));
views.get("lblusertitle").vw.setWidth((int)((80d / 100 * width)));
views.get("lblusertitle").vw.setHeight((int)((40d * scale)));
views.get("lblusertitle").vw.setLeft((int)((50d / 100 * width) - (views.get("lblusertitle").vw.getWidth() / 2)));
views.get("lblusertitle").vw.setTop((int)((views.get("pnframe2").vw.getTop())+(1d / 100 * height)));
views.get("imgedit").vw.setWidth((int)((20d * scale)));
views.get("imgedit").vw.setHeight((int)((views.get("imgedit").vw.getWidth())));
views.get("imgedit").vw.setLeft((int)((views.get("lblusertitle").vw.getLeft() + views.get("lblusertitle").vw.getWidth())-(2d / 100 * width) - (views.get("imgedit").vw.getWidth())));
views.get("imgedit").vw.setTop((int)((views.get("lblusertitle").vw.getTop() + views.get("lblusertitle").vw.getHeight()/2) - (views.get("imgedit").vw.getHeight() / 2)));
views.get("imgsave").vw.setWidth((int)((20d * scale)));
views.get("imgsave").vw.setHeight((int)((views.get("imgsave").vw.getWidth())));
views.get("imgsave").vw.setLeft((int)((views.get("imgedit").vw.getLeft())));
views.get("imgsave").vw.setTop((int)((views.get("imgedit").vw.getTop() + views.get("imgedit").vw.getHeight()/2) - (views.get("imgsave").vw.getHeight() / 2)));
views.get("lblline4").vw.setWidth((int)((90d / 100 * width)));
views.get("lblline4").vw.setHeight((int)((20d * scale)));
views.get("lblline4").vw.setLeft((int)((50d / 100 * width) - (views.get("lblline4").vw.getWidth() / 2)));
views.get("lblline4").vw.setTop((int)((views.get("lblusertitle").vw.getTop() + views.get("lblusertitle").vw.getHeight())));
views.get("lblfullname").vw.setWidth((int)((80d / 100 * width)));
views.get("lblfullname").vw.setHeight((int)((40d * scale)));
views.get("lblfullname").vw.setLeft((int)((50d / 100 * width) - (views.get("lblfullname").vw.getWidth() / 2)));
views.get("lblfullname").vw.setTop((int)((views.get("lblline4").vw.getTop() + views.get("lblline4").vw.getHeight())));
views.get("pnfullname").vw.setWidth((int)((80d / 100 * width)));
views.get("pnfullname").vw.setHeight((int)((50d * scale)));
views.get("pnfullname").vw.setLeft((int)((50d / 100 * width) - (views.get("pnfullname").vw.getWidth() / 2)));
views.get("pnfullname").vw.setTop((int)((views.get("lblfullname").vw.getTop() + views.get("lblfullname").vw.getHeight())));
views.get("txtfullname").vw.setWidth((int)((60d / 100 * width)));
views.get("imgfullname").vw.setHeight((int)((20d * scale)));
views.get("imgfullname").vw.setWidth((int)((views.get("imgfullname").vw.getHeight())));
views.get("imgfullname").vw.setTop((int)((views.get("pnfullname").vw.getHeight())/2d-(views.get("imgfullname").vw.getHeight())/2d));
views.get("lblemail").vw.setWidth((int)((views.get("lblfullname").vw.getWidth())));
views.get("lblemail").vw.setHeight((int)((views.get("lblfullname").vw.getHeight())));
views.get("lblemail").vw.setLeft((int)((views.get("lblfullname").vw.getLeft())));
views.get("lblemail").vw.setTop((int)((views.get("pnfullname").vw.getTop() + views.get("pnfullname").vw.getHeight())));
views.get("pnemail").vw.setWidth((int)((views.get("pnfullname").vw.getWidth())));
views.get("pnemail").vw.setHeight((int)((views.get("pnfullname").vw.getHeight())));
views.get("pnemail").vw.setLeft((int)((views.get("pnfullname").vw.getLeft())));
views.get("pnemail").vw.setTop((int)((views.get("lblemail").vw.getTop() + views.get("lblemail").vw.getHeight())));
views.get("txtemail").vw.setWidth((int)((views.get("txtfullname").vw.getWidth())));
views.get("imgemail").vw.setHeight((int)((views.get("imgfullname").vw.getWidth())));
views.get("imgemail").vw.setWidth((int)((views.get("imgfullname").vw.getHeight())));
views.get("imgemail").vw.setTop((int)((views.get("pnemail").vw.getHeight())/2d-(views.get("imgemail").vw.getHeight())/2d));
views.get("lblpassword").vw.setWidth((int)((views.get("lblfullname").vw.getWidth())));
views.get("lblpassword").vw.setHeight((int)((views.get("lblfullname").vw.getHeight())));
views.get("lblpassword").vw.setLeft((int)((views.get("lblfullname").vw.getLeft())));
views.get("lblpassword").vw.setTop((int)((views.get("pnemail").vw.getTop() + views.get("pnemail").vw.getHeight())));
views.get("pnpassword").vw.setWidth((int)((views.get("pnfullname").vw.getWidth())));
views.get("pnpassword").vw.setHeight((int)((views.get("pnfullname").vw.getHeight())));
views.get("pnpassword").vw.setLeft((int)((views.get("pnfullname").vw.getLeft())));
views.get("pnpassword").vw.setTop((int)((views.get("lblpassword").vw.getTop() + views.get("lblpassword").vw.getHeight())));
views.get("txtpassword").vw.setWidth((int)((views.get("txtfullname").vw.getWidth())));
views.get("imgpassword").vw.setHeight((int)((views.get("imgfullname").vw.getWidth())));
views.get("imgpassword").vw.setWidth((int)((views.get("imgfullname").vw.getHeight())));
views.get("imgpassword").vw.setTop((int)((views.get("pnpassword").vw.getHeight())/2d-(views.get("imgpassword").vw.getHeight())/2d));
views.get("lblphone").vw.setWidth((int)((views.get("lblfullname").vw.getWidth())));
views.get("lblphone").vw.setHeight((int)((views.get("lblfullname").vw.getHeight())));
views.get("lblphone").vw.setLeft((int)((views.get("lblfullname").vw.getLeft())));
views.get("lblphone").vw.setTop((int)((views.get("pnpassword").vw.getTop() + views.get("pnpassword").vw.getHeight())));
views.get("pnphone").vw.setWidth((int)((views.get("pnfullname").vw.getWidth())));
views.get("pnphone").vw.setHeight((int)((views.get("pnfullname").vw.getHeight())));
views.get("pnphone").vw.setLeft((int)((views.get("pnfullname").vw.getLeft())));
views.get("pnphone").vw.setTop((int)((views.get("lblphone").vw.getTop() + views.get("lblphone").vw.getHeight())));
views.get("txtphone").vw.setWidth((int)((views.get("txtfullname").vw.getWidth())));
views.get("imgphone").vw.setHeight((int)((views.get("imgfullname").vw.getWidth())));
views.get("imgphone").vw.setWidth((int)((views.get("imgfullname").vw.getHeight())));
views.get("imgphone").vw.setTop((int)((views.get("pnphone").vw.getHeight())/2d-(views.get("imgphone").vw.getHeight())/2d));
views.get("lblcertificate").vw.setWidth((int)((views.get("lblfullname").vw.getWidth())));
views.get("lblcertificate").vw.setHeight((int)((views.get("lblfullname").vw.getHeight())));
views.get("lblcertificate").vw.setLeft((int)((views.get("lblfullname").vw.getLeft())));
views.get("lblcertificate").vw.setTop((int)((views.get("pnphone").vw.getTop() + views.get("pnphone").vw.getHeight())));
views.get("btncertificate").vw.setWidth((int)((80d / 100 * width)));
views.get("btncertificate").vw.setHeight((int)((50d * scale)));
views.get("btncertificate").vw.setLeft((int)((50d / 100 * width) - (views.get("btncertificate").vw.getWidth() / 2)));
views.get("btncertificate").vw.setTop((int)((views.get("lblcertificate").vw.getTop() + views.get("lblcertificate").vw.getHeight())));
views.get("lblbottom").vw.setWidth((int)((100d / 100 * width)));
views.get("lblbottom").vw.setHeight((int)((80d * scale)));
views.get("lblbottom").vw.setLeft((int)((50d / 100 * width) - (views.get("lblbottom").vw.getWidth() / 2)));
views.get("lblbottom").vw.setTop((int)((100d / 100 * height) - (views.get("lblbottom").vw.getHeight())));
views.get("lblhome2").vw.setWidth((int)((25d / 100 * width)));
views.get("lblhome2").vw.setHeight((int)((20d * scale)));
views.get("lblhome2").vw.setLeft((int)((12.5d / 100 * width) - (views.get("lblhome2").vw.getWidth() / 2)));
views.get("lblhome2").vw.setTop((int)((views.get("lblbottom").vw.getTop() + views.get("lblbottom").vw.getHeight())-(1d / 100 * height) - (views.get("lblhome2").vw.getHeight())));
views.get("lblfund2").vw.setWidth((int)((views.get("lblhome2").vw.getWidth())));
views.get("lblfund2").vw.setHeight((int)((views.get("lblhome2").vw.getHeight())));
views.get("lblfund2").vw.setLeft((int)((37.5d / 100 * width) - (views.get("lblfund2").vw.getWidth() / 2)));
views.get("lblfund2").vw.setTop((int)((views.get("lblhome2").vw.getTop() + views.get("lblhome2").vw.getHeight()) - (views.get("lblfund2").vw.getHeight())));
views.get("lblhistory2").vw.setWidth((int)((views.get("lblhome2").vw.getWidth())));
views.get("lblhistory2").vw.setHeight((int)((views.get("lblhome2").vw.getHeight())));
views.get("lblhistory2").vw.setLeft((int)((62.5d / 100 * width) - (views.get("lblhistory2").vw.getWidth() / 2)));
views.get("lblhistory2").vw.setTop((int)((views.get("lblhome2").vw.getTop() + views.get("lblhome2").vw.getHeight()) - (views.get("lblhistory2").vw.getHeight())));
views.get("lbluser2").vw.setWidth((int)((views.get("lblhome2").vw.getWidth())));
views.get("lbluser2").vw.setHeight((int)((views.get("lblhome2").vw.getHeight())));
views.get("lbluser2").vw.setLeft((int)((87.5d / 100 * width) - (views.get("lbluser2").vw.getWidth() / 2)));
views.get("lbluser2").vw.setTop((int)((views.get("lblhome2").vw.getTop() + views.get("lblhome2").vw.getHeight()) - (views.get("lbluser2").vw.getHeight())));
views.get("lblhome").vw.setWidth((int)((25d * scale)));
views.get("lblhome").vw.setHeight((int)((25d * scale)));
views.get("lblhome").vw.setLeft((int)((12.5d / 100 * width) - (views.get("lblhome").vw.getWidth() / 2)));
views.get("lblhome").vw.setTop((int)((views.get("lblhome2").vw.getTop())-(1d / 100 * height) - (views.get("lblhome").vw.getHeight())));
views.get("lblfund").vw.setWidth((int)((views.get("lblhome").vw.getWidth())));
views.get("lblfund").vw.setHeight((int)((views.get("lblhome").vw.getHeight())));
views.get("lblfund").vw.setLeft((int)((37.5d / 100 * width) - (views.get("lblfund").vw.getWidth() / 2)));
views.get("lblfund").vw.setTop((int)((views.get("lblhome").vw.getTop() + views.get("lblhome").vw.getHeight()) - (views.get("lblfund").vw.getHeight())));
views.get("lblhistory").vw.setWidth((int)((views.get("lblhome").vw.getWidth())));
views.get("lblhistory").vw.setHeight((int)((views.get("lblhome").vw.getHeight())));
views.get("lblhistory").vw.setLeft((int)((62.5d / 100 * width) - (views.get("lblhistory").vw.getWidth() / 2)));
views.get("lblhistory").vw.setTop((int)((views.get("lblhome").vw.getTop() + views.get("lblhome").vw.getHeight()) - (views.get("lblhistory").vw.getHeight())));
views.get("lbluser").vw.setWidth((int)((views.get("lblhome").vw.getWidth())));
views.get("lbluser").vw.setHeight((int)((views.get("lblhome").vw.getHeight())));
views.get("lbluser").vw.setLeft((int)((87.5d / 100 * width) - (views.get("lbluser").vw.getWidth() / 2)));
views.get("lbluser").vw.setTop((int)((views.get("lblhome").vw.getTop() + views.get("lblhome").vw.getHeight()) - (views.get("lbluser").vw.getHeight())));

}
}